language: php
php:
  - 7.3
  - 7.4
dist: xenial
services:
  - docker
before_install:
  - cd tests/TestServer && docker build -t satis-dev .
  - docker run -d -p 8000:80 satis-dev
before_script:
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=clover.xml
after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.3.0/php-coveralls.phar
  - php php-coveralls.phar --verbose
cache:
  directories:
    - $HOME/.composer/cache/files
after_success:
  - bash <(curl -s https://codecov.io/bash)